name: Lint, Test & Deploy
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run Lint
        run: npm run lint
      - name: Run Tests
        run: npm test
      - name: Build project
        run: npm run build
      - name: Deploy code
        run: echo "Deploying ..."
